class Consts {
  final videosURLs = {
    0: {'name': 'Introdução', 'url': 'hcyUZaGIudw'},
    1: {'name': 'Para que estou na Terra?', 'url': 'IrhzOATA-Gk'},
    2: {'name': 'Você não é um acidente', 'url': 'uQ-cspB-pe8'},
    3: {'name': '', 'url': ''},
    4: {'name': '', 'url': ''},
    5: {'name': '', 'url': ''},
    6: {'name': '', 'url': ''},
    7: {'name': '', 'url': ''},
    8: {'name': '', 'url': ''},
    9: {'name': '', 'url': ''},
    10: {'name': '', 'url': ''},
    11: {'name': '', 'url': ''},
    12: {'name': '', 'url': ''},
    13: {'name': '', 'url': ''},
    14: {'name': '', 'url': ''},
    15: {'name': '', 'url': ''},
    16: {'name': '', 'url': ''},
    17: {'name': '', 'url': ''},
    18: {'name': '', 'url': ''},
    19: {'name': '', 'url': ''},
    20: {'name': '', 'url': ''},
    21: {'name': '', 'url': ''},
    22: {'name': '', 'url': ''},
    23: {'name': '', 'url': ''},
    24: {'name': '', 'url': ''},
    25: {'name': '', 'url': ''},
    26: {'name': '', 'url': ''},
    27: {'name': '', 'url': ''},
    28: {'name': '', 'url': ''},
    29: {'name': '', 'url': ''},
    30: {'name': '', 'url': ''},
    31: {'name': '', 'url': ''},
    32: {'name': '', 'url': ''},
    33: {'name': '', 'url': ''},
    34: {'name': '', 'url': ''},
    35: {'name': '', 'url': ''},
    36: {'name': '', 'url': ''},
    37: {'name': '', 'url': ''},
    38: {'name': '', 'url': ''},
    39: {'name': '', 'url': ''},
    40: {'name': '', 'url': ''},
  };
}
